language: python

python:
 - 3.5

services: postgresql

env:
  global:
      - DJANGO="1.11.6"
      - DJANGO_SETTINGS_MODULE="jatszohaz.settings"
      - PYTHONPATH="/home/travis/build/ndarville/pony-forum"
      - PIP_USE_MIRRORS=true
# Last two for OS X, courtesy of stackoverflow.com/a/22697917/419005
# - CFLAGS=-Qunused-arguments
# - CPPFLAGS=-Qunused-arguments

install:
  - pip install -r requirements.txt
  - pip install flake8
    #  - pip install coveralls radon

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - sh build.sh
  - flake8 .

after_success:
  - pip freeze
  #- echo Uploading code coverage data ...; coveralls
  #- echo Code complexity scores:; radon cc --min B ../jatszohaz

notifications:
  email:
    on_success: change
    on_failure: always
